version: "2"
linters:
  enable:
    - asciicheck
    - contextcheck
    - errorlint
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - reassign
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errorlint
          - unparam
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
